### PR TITLE
Fix NetBox 2.9.3 compatibility issues

### PR DESCRIPTION
**Pull request by hoanhan101**
This PR:
- Fixes ChangeLoggedModel path as found in #37.
- Updates outdated NetBox config.
- Requires logging in to view the plugin.
- Bumps to 1.1.0

### CODE REVIEW

**Comment by edaniszewski** [comment]
The changes themselves look okay here, but just a few questions:

1. Are all the changes here related to the 2.9.3 compatibility fix? If not, does it make sense to split the different changes into their own PRs for sake of isolation?
2. If this makes the plugin compatible with 2.9.3, does that mean that it breaks backwards compatibility with any previous versions where the ChangeLoggedModel hadn't moved? If so, we'll need to figure out what the best practices are for pinning to versions of netbox. Generally for python, its setting the version in `setup.py`'s `install_requires` field, but given that can be  loaded more dynamically into netbox, I'm not sure if that necessarily works, so its something to read up on.

**Comment by hoanhan101** [comment]
@edaniszewski 

> Are all the changes here related to the 2.9.3 compatibility fix? If not, does it make sense to split the different changes into their own PRs for sake of isolation?

Yes, I believe all the changes here are related to the 2.9.3 compatibility. The NetBox configuration and required login models needs to be happened along with the updated ChangeLoggedModel path.

> If this makes the plugin compatible with 2.9.3, does that mean that it breaks backwards compatibility with any previous versions where the ChangeLoggedModel hadn't moved?

That's a good call. The plugin will probably break our fork which is currently at [v2.8.5](https://github.com/vapor-ware/netbox/commit/bb7191e9538e806ca47393f4abb6adc9f4f3460c) if one bumps it to `1.1.0`. Let's see if I can find what the best practices are for pinning NetBox version. As for now, do you think making a compatibility matrix is good enough as a workaround?

**Comment by edaniszewski** [comment]
I think it _probably_ is, but maybe just take a quick look around to see if you can quickly find anything on version pinning practices for netbox. If nothing obvious comes up, or the process to do it is more intensive than just some configuration, then yeah, a compatibility matrix is good and we can open an issue to tackle the version pinning separately.

**Comment by hoanhan101** [comment]
I'm opening #39 to tackle the version pinning separately as nothing good came up in my finding.

**Review by edaniszewski — APPROVED** [review]

**Pull request merged**
